name: "Remove label"
on:
  pull_request:
    types:
      - closed
permissions:
  contents: read
  pull-requests: write

jobs:
  remove_label:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'system')
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const labels = ${{ toJSON(github.event.pull_request.labels) }}
            const label = labels.find(label => label.name.startsWith('system'))
            if (!label) {
              console.log('not found target label')
              return
            }
            const res = await github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: label.name
            })
            if (res.status !== 200) {
              console.error(JSON.stringify(res, null, '  '))
              throw new Error('API Error')
            }